name: ItemSpawners
version: '${project.version}'
main: dev.dontblameme.itemspawners.main.ItemSpawners
api-version: 1.19
depend: [ UtilsAPI ]
authors: [ DontBlameMe ]
commands:
  SetSpawner:
    description: Sets a new spawner
  GetSpawners:
    description: Gets all spawners
  DeleteSpawner:
    description: Deletes a spawner
  ConfigReload:
    description: Reloads the config.yml